Implement steps 1-4
dgomon/feed-exercise pull request #1
Opened 2021-06-22 18:08 UTC by dgomon

Hi Nissim,

Following up on our conversation on Monday, I created this this interim PR to contain steps 1-4 of the third exercise. Also, I addressed your concern of Kotlin vs. Java stream style data conversion in FeedRepository.kt:25.

In the meantime I am proceeding to step 5.

Cheers,
Dmitri

2021-06-27 11:59 UTC, nissimLightricks requested changes
Good job 👏 . Round.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +    }
This property should be private. Also in the repository I would not expect to have `LiveData` object. The main purpose of the `LiveData` is to have observer that are lifecycle aware of the android components. Better to have in this class RxJava objects that are more rich in terms of api/operators they provides. Also we can observe it without providing it a lifecycle object.  Although we can observe a livedata without a lifecycle object with observeForever/removeObserver but the api is more complicate since we have to store the livedata reference and observer reference in order to remove the observation.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +class FeedRepository (private val feedApiService: FeedApiService, private val feedDatabase: FeedDatabase) {
The issue I have with the repository api's is that we have to call refresh manually in order to get for the first time data. I would expect that this logic is done by the code without the need to manually refreshing the cache when it is empty/expired.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/data/Models.kt
> +    val templatesMetadata: List<FeedItem>
This one should move into the network package.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +    private val serialDisposable = SerialDisposable()
This disposable is never disposed. Please dispose it on `onCleared` of the view model.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +    private val feedItems = repository.feedItems
The isEmpty property has to be synchronized with the feetItems property so whenever we have to make the sync by ourself is error prone. I would rather wrap this two fields into an object that will sync for us.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +        isEmpty.value = feedItems.value.isNullOrEmpty()
We can get a race here. Your assumption is that when the `handleResponse` is invoked that the feedItems has value. But this assumption is wrong when working with async methods we shouldn't depend on such assumptions. Because we can get races between the call to our handleResponse method and the set of the feedItems property with the new values.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +        networkErrorEvent.postValue(Event(error.toString()))
As we talk F2F we should avoid using postValue but rather setValue.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +    private lateinit var mFeedApiService: FeedApiService
Please remove the `m` before the member variable we don't have such a convention.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +    fun testRefresh() {
Remove the word `test` from the method. All methods with the test annotation is a test method. We don't need more information than that.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +            .awaitTerminalEvent()
We shouldn't depend on the real scheduler on test. See:

RxAndroidPlugins.setMainThreadSchedulerHandler { Schedulers.trampoline() }
RxJavaPlugins.setComputationSchedulerHandler { Schedulers.trampoline() }
RxJavaPlugins.setIoSchedulerHandler { Schedulers.trampoline() }
RxJavaPlugins.setSingleSchedulerHandler { Schedulers.trampoline() }

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        val feedExpected: Feed = mFeedApiService.getFeed().blockingGet()
same as previous.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        val itemsInRepository = feedRepository.feedItems.blockingObserve()
I am not sure I understand let's talk on it F2F.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        return Single.just(feed)
Why not simply defining objects here and returning a list of them. That way our tests will not depends on moshi or the json file.

2021-06-27 11:59 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +            .awaitTerminalEvent()
So the test tests the case that the cache has been refreshed. So what should happen in the case it wasn't?

2021-06-27 12:42 UTC, dgomon commented on app/src/main/java/FeedExerciseApplication.kt
> +}
DONE

2021-06-27 12:47 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +            .observeOn(Schedulers.io())
removed `.observeOn(Schedulers.io()) `

2021-06-27 12:47 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +fun List<FeedItemEntity>.toFeedItems(): List<FeedItem> { return map {
Changed to private

2021-06-27 12:47 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +fun List<FeedItem>.toFeedItemEntities(): List<FeedItemEntity> { return map {
Changed to private

2021-06-27 12:48 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +class FeedRepository (private val feedApiService: FeedApiService, private val feedDatabase: FeedDatabase) {
Line shortened, space removed

2021-06-27 12:49 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/DataAccessObjects.kt
> +}
EOF added

2021-06-27 13:04 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +fun List<FeedItemEntity>.toFeedItems(): List<FeedItem> { return map {
Update: setting visibility modifier to private breaks `FeedRepositoryTest.testRefresh()` which uses `toFeedItems()`. The test gets broken even if `toFeedItems()` is annotated with `@VisibleForTesting`.

2021-06-27 13:04 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/FeedRepository.kt
> +fun List<FeedItem>.toFeedItemEntities(): List<FeedItemEntity> { return map {
Restored to public, see above

2021-06-27 13:06 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +    fun testRefresh() {
DONE

2021-06-27 14:37 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/DataAccessObjects.kt
> +    fun getCount(): Int
Method renamed

2021-06-27 14:42 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/Entities.kt
> +    @PrimaryKey val id: String,
That's because `public @interface PrimaryKey` in  `androidx.room.PrimaryKey.java` doesn't contain declaration of `name()`. `androidx.room.ColumnInfo.java` contains the declaration:
`String name() default INHERIT_FIELD_NAME;`

2021-06-27 14:42 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/FeedDatabase.kt
> +        }
Method removed

2021-06-27 14:42 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/FeedDatabase.kt
> +        }
DONE

2021-06-27 14:45 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/network/FeedApiService.kt
> +        const val BASE_URL      = "https://assets.swishvideoapp.com/Android/demo/"
Extra space removed. Setting  access modifier of`THUMBNAIL_URL` to private results in access error in FeedRepository.kt, I suggest to keep visibility of `BASE_URL` as public for consistency.

2021-06-27 14:45 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/network/FeedApiService.kt
> +        const val BASE_URL      = "https://assets.swishvideoapp.com/Android/demo/"
see above

2021-06-27 14:48 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +open class FeedViewModel(private val repository: FeedRepository) : ViewModel() {
I suspect that's in order to support testing with the `Mock` framework, which can test only open classes/methods. I think, the designer of the exercise can provide a more accurate answer.

2021-06-27 14:48 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/network/FeedApiService.kt
> +        }
DONE

2021-06-27 15:00 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/network/FeedApiService.kt
> +    fun getFeed(): Single<Feed>
Roger that, `Feed` refactored to DataTransferObjects.kt

2021-06-27 15:06 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/Models.kt
> +)
I'm not sure I understand the comment. Can you please elaborate?

2021-06-27 15:07 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/Models.kt
> +    val templatesMetadata: List<FeedItem>
DONE

2021-06-27 15:07 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +    private val serialDisposable = SerialDisposable()
DONE

2021-06-27 15:08 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +    private val feedItems = repository.feedItems
Leaving the code as is, as per our discussion

2021-06-27 15:08 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +        isEmpty.value = feedItems.value.isNullOrEmpty()
Leaving the code as is, as per our discussion

2021-06-27 15:08 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +        networkErrorEvent.postValue(Event(error.toString()))
DONE

2021-06-27 15:09 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +    private lateinit var mFeedApiService: FeedApiService
DONE

2021-06-27 15:19 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +            .awaitTerminalEvent()
Scheduler replaced.
Re: in the case it wasn't: the `assert` statements in lines 74-75 and 79-80 will fail, won't they?

2021-06-27 15:19 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        val itemsInRepository = feedRepository.feedItems.blockingObserve()
OK

2021-06-27 16:04 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        return Single.just(feed)
DONE

2021-06-27 16:06 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/database/Entities.kt
> +    @PrimaryKey val id: String,
You should add in addition to `@PrimaryKey` a `@ColumnInfo` annotation.

2021-06-27 16:06 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/ui/feed/FeedViewModel.kt
> +open class FeedViewModel(private val repository: FeedRepository) : ViewModel() {
Didn't see that it was there.

2021-06-27 16:07 UTC, nissimLightricks commented on app/src/main/java/com/lightricks/feedexercise/data/Models.kt
> +)
This class shouldn't change due to the add of the network. This object shouldn't be in use by the network layer. Create a dedicated DTO for it.

2021-06-27 16:09 UTC, nissimLightricks commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +            .awaitTerminalEvent()
Right.

2021-06-27 18:46 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/Entities.kt
> +    @PrimaryKey val id: String,
DONE

2021-06-27 19:00 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/data/Models.kt
> +)
DONE

2021-06-28 09:04 UTC, dgomon commented on app/src/main/java/com/lightricks/feedexercise/database/DataAccessObjects.kt
> +    fun getAll(): LiveData<List<FeedItemEntity>>
DONE

2021-06-28 12:01 UTC, dgomon commented on app/src/androidTest/java/com/lightricks/feedexercise/data/FeedRepositoryTest.kt
> +        val feedExpected: Feed = mFeedApiService.getFeed().blockingGet()
DONE. The assignment needs to be updated:

- Remove `Verifying that a value is eventually set for a ​LiveData​ requires blocking the test.
Tip: The extension function called ​blockingObserve()​ comes to the rescue. Look for it in ​FeedRepositoryTest.kt​ ` from page 8 in the assignment.

2021-06-28 12:33 UTC, nissimLightricks requested changes
Excellent! Squash.

2021-07-26 14:49 UTC, closed without merging